/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.personalfinances.view;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author OneTouchESPE
 */
public class FrmAdminMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public FrmAdminMainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/GroupIcon.jpeg"));
        icon = new ImageIcon(icon.getImage().getScaledInstance(100, 50, Image.SCALE_DEFAULT));
        lblGroupIcon.setIcon(icon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        lblGroupIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblPhrase = new javax.swing.JLabel();
        lblClusterConfiguration = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnClusterConfiguration = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbConfigurationURI = new javax.swing.JLabel();
        lblAdministratorMenu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuPersonalFinances = new javax.swing.JMenu();
        mnuItmLogOut = new javax.swing.JMenuItem();
        mnuItmExit = new javax.swing.JMenuItem();
        mnuSettings = new javax.swing.JMenu();
        mnuItmChangeUsername = new javax.swing.JMenuItem();
        mnuItmChangePassword = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personal Finances");
        setResizable(false);
        setSize(new java.awt.Dimension(900, 700));

        lblGroupIcon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setText("Welcome to Personal Finances");

        lblPhrase.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        lblPhrase.setText("Let's manage your money together. Enjoy it !");

        lblClusterConfiguration.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClusterConfiguration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClusterConfiguration.setText("Cluster Configuration");

        lblExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("EXIT");

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Exit64.png"))); // NOI18N
        btnExit.setToolTipText("Click to Exit.");
        btnExit.setContentAreaFilled(false);
        btnExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Exit128.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnClusterConfiguration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/configurationDataBase.png"))); // NOI18N
        btnClusterConfiguration.setToolTipText("Click to go to Statement's Menu");
        btnClusterConfiguration.setContentAreaFilled(false);
        btnClusterConfiguration.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/configurationDataBase.png"))); // NOI18N
        btnClusterConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClusterConfigurationActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ProjectIcon.png"))); // NOI18N

        lbConfigurationURI.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        lblAdministratorMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAdministratorMenu.setText("Administrator Menu");

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlMenuLayout.createSequentialGroup()
                                    .addComponent(lbConfigurationURI)
                                    .addGap(161, 161, 161))
                                .addGroup(pnlMenuLayout.createSequentialGroup()
                                    .addComponent(lblClusterConfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)))
                            .addGroup(pnlMenuLayout.createSequentialGroup()
                                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)))
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMenuLayout.createSequentialGroup()
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(lblGroupIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnClusterConfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdministratorMenu)
                            .addGroup(pnlMenuLayout.createSequentialGroup()
                                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPhrase, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62))))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPhrase, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblGroupIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMenuLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btnClusterConfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMenuLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblAdministratorMenu)
                                .addGap(50, 50, 50)
                                .addComponent(lblClusterConfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMenuLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbConfigurationURI))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        mnuPersonalFinances.setText("Personal Finances");
        mnuPersonalFinances.setToolTipText("Click to display a menu.");

        mnuItmLogOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnuItmLogOut.setText("Log out");
        mnuItmLogOut.setToolTipText("Click to log out and change the user.");
        mnuItmLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmLogOutActionPerformed(evt);
            }
        });
        mnuPersonalFinances.add(mnuItmLogOut);

        mnuItmExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        mnuItmExit.setText("Exit");
        mnuItmExit.setToolTipText("Click to exit.");
        mnuItmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmExitActionPerformed(evt);
            }
        });
        mnuPersonalFinances.add(mnuItmExit);

        jMenuBar1.add(mnuPersonalFinances);

        mnuSettings.setText("Settings");

        mnuItmChangeUsername.setText("Change Username");
        mnuItmChangeUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmChangeUsernameActionPerformed(evt);
            }
        });
        mnuSettings.add(mnuItmChangeUsername);

        mnuItmChangePassword.setText("Change Password");
        mnuItmChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmChangePasswordActionPerformed(evt);
            }
        });
        mnuSettings.add(mnuItmChangePassword);

        jMenuBar1.add(mnuSettings);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void mnuItmLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmLogOutActionPerformed
        this.setVisible(false);
        new FrmLogin().setVisible(true);
    }//GEN-LAST:event_mnuItmLogOutActionPerformed

    private void mnuItmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuItmExitActionPerformed

    private void mnuItmChangeUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmChangeUsernameActionPerformed
        this.setVisible(false);
        new FrmChangeUsername().setVisible(true);
    }//GEN-LAST:event_mnuItmChangeUsernameActionPerformed

    private void mnuItmChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmChangePasswordActionPerformed
        this.setVisible(false);
        new FrmChangePassword().setVisible(true);
    }//GEN-LAST:event_mnuItmChangePasswordActionPerformed

    private void btnClusterConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClusterConfigurationActionPerformed
        this.setVisible(false);
        new FrmClusterConfiguration().setVisible(true);
    }//GEN-LAST:event_btnClusterConfigurationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdminMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClusterConfiguration;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbConfigurationURI;
    private javax.swing.JLabel lblAdministratorMenu;
    private javax.swing.JLabel lblClusterConfiguration;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblGroupIcon;
    private javax.swing.JLabel lblPhrase;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenuItem mnuItmChangePassword;
    private javax.swing.JMenuItem mnuItmChangeUsername;
    private javax.swing.JMenuItem mnuItmExit;
    private javax.swing.JMenuItem mnuItmLogOut;
    private javax.swing.JMenu mnuPersonalFinances;
    private javax.swing.JMenu mnuSettings;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
