/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.personalfinances.view;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import ec.edu.espe.personalfinances.controller.FrameManager;
import ec.edu.espe.personalfinances.model.Expense;
import ec.edu.espe.personalfinances.model.OtherCategoryExpense;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author OneTouchESPE
 */
public class FrmExpenseOtherCategory extends javax.swing.JFrame {

    private final String directory = System.getProperties().getProperty("user.dir");
    DefaultComboBoxModel newCategoryComboBox = new DefaultComboBoxModel();

    /**
     * Creates new form FrmExpenseEntertainment
     */
    public FrmExpenseOtherCategory() {
        initComponents();
        this.setLocationRelativeTo(null);

        File archivo = null;
        FileReader fileReader = null;
        BufferedReader bufferReader = null;
        ArrayList<OtherCategoryExpense> newCategory = new ArrayList<>();
        Gson gson = new Gson();
        String line;
        String newCategoryJson = "";

        try {
            archivo = new File(directory + "\\OtherCategoryExpense.json");
            fileReader = new FileReader(archivo);
            bufferReader = new BufferedReader(fileReader);

            while ((line = bufferReader.readLine()) != null) {
                System.out.println(line);

                newCategoryJson = newCategoryJson + line;

            }
            java.lang.reflect.Type newCategoryType = new TypeToken<ArrayList<OtherCategoryExpense>>() {
            }.getType();
            newCategory = gson.fromJson(newCategoryJson, newCategoryType);
            for (OtherCategoryExpense categories : newCategory) {
                newCategoryComboBox.addElement(categories.getOtherCategory());
            }
            CmbBoxOtherCategory.setModel(newCategoryComboBox);
        } catch (Exception e) {
        } finally {
            try {
                if (null != fileReader) {
                    fileReader.close();
                }
            } catch (IOException e2) {
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOtherCategoryData = new javax.swing.JPanel();
        lblAmountOtherCategory = new javax.swing.JLabel();
        lblEstablishmentOtherCategory = new javax.swing.JLabel();
        txtEstablishmentOtherCategory = new javax.swing.JTextField();
        lblDateOtherCategory = new javax.swing.JLabel();
        lblPaymentMethodOtherCategory = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblNewCategory = new javax.swing.JLabel();
        dtcDateOtherCategory = new com.toedter.calendar.JDateChooser();
        chbxCash = new java.awt.Checkbox();
        chbxDebitCard = new java.awt.Checkbox();
        chbxCreditCard = new java.awt.Checkbox();
        txtAmountOtherCategory = new javax.swing.JTextField();
        CmbBoxOtherCategory = new javax.swing.JComboBox<>();
        lbExpenseOtherCategory = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblButtons = new javax.swing.JPanel();
        btnSaveOtherCategory = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        bttnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Expense/Other Category");
        setResizable(false);

        lblAmountOtherCategory.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblAmountOtherCategory.setText("Amount:");

        lblEstablishmentOtherCategory.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblEstablishmentOtherCategory.setText("Establishment :");

        txtEstablishmentOtherCategory.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtEstablishmentOtherCategory.setToolTipText("Type establishment's information about your expense.");

        lblDateOtherCategory.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblDateOtherCategory.setText("Date :");
        lblDateOtherCategory.setToolTipText("Choose the date of your expense transaction.");

        lblPaymentMethodOtherCategory.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblPaymentMethodOtherCategory.setText("Payment Method");
        lblPaymentMethodOtherCategory.setToolTipText("Choose the payment method that you used.");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/EstablishmentExpense.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ValueExpense.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DateExpense.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PayModeExpense.png"))); // NOI18N

        lblNewCategory.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblNewCategory.setText("New Category:");

        dtcDateOtherCategory.setToolTipText("Choose the date of your expense transaction.");
        dtcDateOtherCategory.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        chbxCash.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        chbxCash.setLabel("Cash");

        chbxDebitCard.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        chbxDebitCard.setLabel("Debit Card");

        chbxCreditCard.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        chbxCreditCard.setLabel("Credit Card");

        txtAmountOtherCategory.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtAmountOtherCategory.setToolTipText("Type numbers and decimal point only.");
        txtAmountOtherCategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountOtherCategoryKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlOtherCategoryDataLayout = new javax.swing.GroupLayout(pnlOtherCategoryData);
        pnlOtherCategoryData.setLayout(pnlOtherCategoryDataLayout);
        pnlOtherCategoryDataLayout.setHorizontalGroup(
            pnlOtherCategoryDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOtherCategoryDataLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(pnlOtherCategoryDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlOtherCategoryDataLayout.createSequentialGroup()
                        .addGroup(pnlOtherCategoryDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(pnlOtherCategoryDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlOtherCategoryDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmountOtherCategory)
                            .addComponent(lblPaymentMethodOtherCategory)
                            .addComponent(lblDateOtherCategory)
                            .addComponent(lblEstablishmentOtherCategory))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlOtherCategoryDataLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblNewCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnlOtherCategoryDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtcDateOtherCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlOtherCategoryDataLayout.createSequentialGroup()
                        .addComponent(chbxCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbxDebitCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbxCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlOtherCategoryDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtAmountOtherCategory, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEstablishmentOtherCategory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addComponent(CmbBoxOtherCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlOtherCategoryDataLayout.setVerticalGroup(
            pnlOtherCategoryDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOtherCategoryDataLayout.createSequentialGroup()
                .addGroup(pnlOtherCategoryDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOtherCategoryDataLayout.createSequentialGroup()
                        .addComponent(lblNewCategory)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(pnlOtherCategoryDataLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(CmbBoxOtherCategory)))
                .addGap(18, 18, 18)
                .addGroup(pnlOtherCategoryDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOtherCategoryDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEstablishmentOtherCategory)
                        .addComponent(txtEstablishmentOtherCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOtherCategoryDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmountOtherCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmountOtherCategory, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnlOtherCategoryDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOtherCategoryDataLayout.createSequentialGroup()
                        .addComponent(lblDateOtherCategory)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOtherCategoryDataLayout.createSequentialGroup()
                        .addGroup(pnlOtherCategoryDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlOtherCategoryDataLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(dtcDateOtherCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(27, 27, 27)))
                .addGroup(pnlOtherCategoryDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlOtherCategoryDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(chbxCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPaymentMethodOtherCategory)
                        .addComponent(chbxDebitCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chbxCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );

        lbExpenseOtherCategory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbExpenseOtherCategory.setText("OTHER CATEGORY");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Plus.png"))); // NOI18N

        btnSaveOtherCategory.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnSaveOtherCategory.setText("Save");
        btnSaveOtherCategory.setToolTipText("Click to save your expense information.");
        btnSaveOtherCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveOtherCategoryActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setToolTipText("Click to reset/delete the fields.");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        bttnReturn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        bttnReturn.setText("Return");
        bttnReturn.setToolTipText("Click to return to the Expense menu.");
        bttnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lblButtonsLayout = new javax.swing.GroupLayout(lblButtons);
        lblButtons.setLayout(lblButtonsLayout);
        lblButtonsLayout.setHorizontalGroup(
            lblButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSaveOtherCategory)
                .addGap(31, 31, 31)
                .addComponent(btnReset)
                .addGap(28, 28, 28)
                .addComponent(bttnReturn)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        lblButtonsLayout.setVerticalGroup(
            lblButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveOtherCategory)
                    .addComponent(btnReset)
                    .addComponent(bttnReturn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(lbExpenseOtherCategory))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOtherCategoryData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(lblButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lbExpenseOtherCategory))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(pnlOtherCategoryData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveOtherCategoryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveOtherCategoryActionPerformed
    {//GEN-HEADEREND:event_btnSaveOtherCategoryActionPerformed
        Expense expense = new Expense();
        FrameManager frameManager = new FrameManager();
        expense.setExpense(lbExpenseOtherCategory.getText());
        expense.setAmount(txtAmountOtherCategory.getText());
        expense.setEstablishment(CmbBoxOtherCategory.toString());
        expense.setDate(dtcDateOtherCategory.getDate().toString());

        if (chbxCash.getState() == true) {
            expense.setPaymentMethod(chbxCash.getLabel());
        }
        if (chbxDebitCard.getState() == true) {
            expense.setPaymentMethod(chbxDebitCard.getLabel());
        }
        if (chbxCreditCard.getState() == true) {
            expense.setPaymentMethod(chbxCreditCard.getLabel());
        }

        frameManager.saveExpense(expense);
        JOptionPane.showMessageDialog(this, "Save Data");


    }//GEN-LAST:event_btnSaveOtherCategoryActionPerformed


    private void btnResetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnResetActionPerformed
    {//GEN-HEADEREND:event_btnResetActionPerformed
        // TODO add your handling code here:

        txtEstablishmentOtherCategory.setText(null);
        CmbBoxOtherCategory.setSelectedItem(null);
        txtAmountOtherCategory.setText(null);
        dtcDateOtherCategory.setDate(null);
        chbxCash.setState(false);
        chbxDebitCard.setState(false);
        chbxCreditCard.setState(false);


    }//GEN-LAST:event_btnResetActionPerformed

    private void bttnReturnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bttnReturnActionPerformed
    {//GEN-HEADEREND:event_bttnReturnActionPerformed
        // TODO add your handling code here:
        FrmExpense frmExpense = new FrmExpense();
        frmExpense.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttnReturnActionPerformed

    private void txtAmountOtherCategoryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountOtherCategoryKeyTyped
        char limitChar = evt.getKeyChar();
        if (!Character.isDigit(limitChar) && limitChar != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txtAmountOtherCategoryKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmExpenseOtherCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmExpenseOtherCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmExpenseOtherCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmExpenseOtherCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmExpenseOtherCategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbBoxOtherCategory;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSaveOtherCategory;
    private javax.swing.JButton bttnReturn;
    private java.awt.Checkbox chbxCash;
    private java.awt.Checkbox chbxCreditCard;
    private java.awt.Checkbox chbxDebitCard;
    private com.toedter.calendar.JDateChooser dtcDateOtherCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbExpenseOtherCategory;
    private javax.swing.JLabel lblAmountOtherCategory;
    private javax.swing.JPanel lblButtons;
    private javax.swing.JLabel lblDateOtherCategory;
    private javax.swing.JLabel lblEstablishmentOtherCategory;
    private javax.swing.JLabel lblNewCategory;
    private javax.swing.JLabel lblPaymentMethodOtherCategory;
    private javax.swing.JPanel pnlOtherCategoryData;
    private javax.swing.JTextField txtAmountOtherCategory;
    private javax.swing.JTextField txtEstablishmentOtherCategory;
    // End of variables declaration//GEN-END:variables
}
