/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.personalfinances.view;

import javax.swing.JOptionPane;

import ec.edu.espe.personalfinances.controller.FrameManager;
import ec.edu.espe.personalfinances.model.Expense;

/**
 *
 * @author OneTouchESPE
 */
public class FrmExpenseFood extends javax.swing.JFrame {

    public FrmExpenseFood() {

        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlFoodData = new javax.swing.JPanel();
        lblFoodAmount = new javax.swing.JLabel();
        lblFoodEstablishment = new javax.swing.JLabel();
        txtEstablishmentFood = new javax.swing.JTextField();
        lblDateFood = new javax.swing.JLabel();
        lblPaymentMethod = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnSaveFood = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        bttnReturn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dateFood = new com.toedter.calendar.JDateChooser();
        chbxCashFood = new java.awt.Checkbox();
        chbxDebitCardFood = new java.awt.Checkbox();
        chbxCreditCardFood = new java.awt.Checkbox();
        txtAmountFood = new javax.swing.JTextField();
        lbExpenseFood = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Food Expense");
        setResizable(false);

        lblFoodAmount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblFoodAmount.setText("Amount:");

        lblFoodEstablishment.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblFoodEstablishment.setText("Establishment :");

        txtEstablishmentFood.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtEstablishmentFood.setToolTipText("Type establishment's information about your expense.");

        lblDateFood.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblDateFood.setText("Date :");
        lblDateFood.setToolTipText("Choose the date of your expense transaction.");

        lblPaymentMethod.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblPaymentMethod.setText("Payment Method");
        lblPaymentMethod.setToolTipText("Choose the payment method that you used.");

        btnSaveFood.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnSaveFood.setText("Save");
        btnSaveFood.setToolTipText("Click to save your expense information.");
        btnSaveFood.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSaveFoodActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setToolTipText("Click to reset/delete the fields.");
        btnReset.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnResetActionPerformed(evt);
            }
        });

        bttnReturn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        bttnReturn.setText("Return");
        bttnReturn.setToolTipText("Click to return to the Expense menu.");
        bttnReturn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bttnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSaveFood)
                .addGap(31, 31, 31)
                .addComponent(btnReset)
                .addGap(28, 28, 28)
                .addComponent(bttnReturn)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveFood)
                    .addComponent(btnReset)
                    .addComponent(bttnReturn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/EstablishmentExpense.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ValueExpense.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DateExpense.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PayModeExpense.png"))); // NOI18N

        dateFood.setToolTipText("Choose the date of your expense transaction.");
        dateFood.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        chbxCashFood.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chbxCashFood.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        chbxCashFood.setLabel("Cash");

        chbxDebitCardFood.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        chbxDebitCardFood.setLabel("Debit Card");

        chbxCreditCardFood.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        chbxCreditCardFood.setLabel("Credit Card");

        txtAmountFood.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtAmountFood.setToolTipText("Type numbers and decimal point only.");
        txtAmountFood.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtAmountFoodKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlFoodDataLayout = new javax.swing.GroupLayout(pnlFoodData);
        pnlFoodData.setLayout(pnlFoodDataLayout);
        pnlFoodDataLayout.setHorizontalGroup(
            pnlFoodDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFoodDataLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pnlFoodDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addGroup(pnlFoodDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFoodDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFoodDataLayout.createSequentialGroup()
                        .addGroup(pnlFoodDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFoodAmount)
                            .addComponent(lblPaymentMethod)
                            .addComponent(lblDateFood)
                            .addComponent(lblFoodEstablishment))
                        .addGroup(pnlFoodDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFoodDataLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(chbxCashFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbxDebitCardFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbxCreditCardFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlFoodDataLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(pnlFoodDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtAmountFood, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(txtEstablishmentFood, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(dateFood, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnlFoodDataLayout.setVerticalGroup(
            pnlFoodDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFoodDataLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlFoodDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFoodEstablishment)
                    .addComponent(txtEstablishmentFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlFoodDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFoodAmount)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmountFood, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnlFoodDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateFood, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFoodDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDateFood)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlFoodDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFoodDataLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFoodDataLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(pnlFoodDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPaymentMethod)
                            .addComponent(chbxCashFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbxDebitCardFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbxCreditCardFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lbExpenseFood.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbExpenseFood.setText("FOOD EXPENSE");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/FoodExpense1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFoodData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(110, 110, 110)
                        .addComponent(lbExpenseFood))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbExpenseFood)))
                .addGap(18, 18, 18)
                .addComponent(pnlFoodData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveFoodActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveFoodActionPerformed
    {//GEN-HEADEREND:event_btnSaveFoodActionPerformed
        Expense expense = new Expense();
        FrameManager frameManager = new FrameManager();
        expense.setExpense(lbExpenseFood.getText());
        expense.setAmount(txtAmountFood.getText());
        expense.setEstablishment(txtEstablishmentFood.getText());
        expense.setDate(dateFood.getDate().toString());

        if (chbxCashFood.getState() == true) {
            expense.setPaymentMethod(chbxCashFood.getLabel());
        }
        if (chbxDebitCardFood.getState() == true) {
            expense.setPaymentMethod(chbxDebitCardFood.getLabel());
        }
        if (chbxCreditCardFood.getState() == true) {
            expense.setPaymentMethod(chbxCreditCardFood.getLabel());
        }

        frameManager.saveExpense(expense);
       


    }//GEN-LAST:event_btnSaveFoodActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnResetActionPerformed
    {//GEN-HEADEREND:event_btnResetActionPerformed
        txtEstablishmentFood.setText(null);
        txtAmountFood.setText(null);
        dateFood.setDate(null);
        chbxCashFood.setState(false);
        chbxDebitCardFood.setState(false);
        chbxCreditCardFood.setState(false);
    }//GEN-LAST:event_btnResetActionPerformed

    private void bttnReturnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bttnReturnActionPerformed
    {//GEN-HEADEREND:event_bttnReturnActionPerformed
        FrmExpense frmExpense = new FrmExpense();
        frmExpense.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttnReturnActionPerformed

    private void txtAmountFoodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountFoodKeyTyped
        char limitChar = evt.getKeyChar();
        if (!Character.isDigit(limitChar) && limitChar != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txtAmountFoodKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmExpenseFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmExpenseFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmExpenseFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmExpenseFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmExpenseFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSaveFood;
    private javax.swing.JButton bttnReturn;
    public java.awt.Checkbox chbxCashFood;
    public java.awt.Checkbox chbxCreditCardFood;
    public java.awt.Checkbox chbxDebitCardFood;
    public com.toedter.calendar.JDateChooser dateFood;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel lbExpenseFood;
    private javax.swing.JLabel lblDateFood;
    private javax.swing.JLabel lblFoodAmount;
    private javax.swing.JLabel lblFoodEstablishment;
    private javax.swing.JLabel lblPaymentMethod;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlFoodData;
    public javax.swing.JTextField txtAmountFood;
    public javax.swing.JTextField txtEstablishmentFood;
    // End of variables declaration//GEN-END:variables
}
