/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.personalfinances.view;

/**
 *
 * @author OneTouchESPE
 */
public class FrmExpense extends javax.swing.JFrame {

    /**
     * Creates new form FrmExpense
     */
    public FrmExpense() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlHealthExpense = new javax.swing.JPanel();
        btnHealthExpense = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pnlFoodExpense = new javax.swing.JPanel();
        btnFoodExpense = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlTransportExpense = new javax.swing.JPanel();
        bttnEducationExpense = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlClothesExpense = new javax.swing.JPanel();
        btnClothesExpense = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pnlEntertainmentExpense = new javax.swing.JPanel();
        btnLivingHouseExpense = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pnlOtherCategoryExpense = new javax.swing.JPanel();
        bttnOtherCategory = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnReturnToMainMenu = new javax.swing.JButton();
        btnRegisterCard = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuPersonalFinances = new javax.swing.JMenu();
        mnuItmLogOut = new javax.swing.JMenuItem();
        mnuItmExit = new javax.swing.JMenuItem();
        mnuCustomerInformation = new javax.swing.JMenu();
        mnuIncome = new javax.swing.JMenu();
        mnuItmSalary = new javax.swing.JMenuItem();
        mnuItmPocketMoney = new javax.swing.JMenuItem();
        mnuItmOtherCategoryIncome = new javax.swing.JMenuItem();
        mnuExpense = new javax.swing.JMenu();
        mnuItmFood = new javax.swing.JMenuItem();
        mnuItmEducation = new javax.swing.JMenuItem();
        mnuItmHealth = new javax.swing.JMenuItem();
        mnuItmClothes = new javax.swing.JMenuItem();
        mnuItmLivingHouse = new javax.swing.JMenuItem();
        mnuItmOtherCategoryExpense = new javax.swing.JMenuItem();
        mnuStatement = new javax.swing.JMenu();
        mnuItmTotalIncome = new javax.swing.JMenuItem();
        mnuItmTotalExpense = new javax.swing.JMenuItem();
        mnuItmTotalBalance = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expenses");
        setName("Expense Menu"); // NOI18N
        setResizable(false);

        pnlHealthExpense.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnHealthExpense.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnHealthExpense.setText("Health");
        btnHealthExpense.setToolTipText("Click to add Health Expense information.");
        btnHealthExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHealthExpenseActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/HealthExpense.png"))); // NOI18N

        javax.swing.GroupLayout pnlHealthExpenseLayout = new javax.swing.GroupLayout(pnlHealthExpense);
        pnlHealthExpense.setLayout(pnlHealthExpenseLayout);
        pnlHealthExpenseLayout.setHorizontalGroup(
            pnlHealthExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHealthExpenseLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnHealthExpense)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHealthExpenseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHealthExpenseLayout.setVerticalGroup(
            pnlHealthExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHealthExpenseLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(btnHealthExpense)
                .addContainerGap())
        );

        pnlFoodExpense.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnFoodExpense.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnFoodExpense.setText("Food");
        btnFoodExpense.setToolTipText("Click to add Food Expense information.");
        btnFoodExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodExpenseActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/FoodExpense.png"))); // NOI18N

        javax.swing.GroupLayout pnlFoodExpenseLayout = new javax.swing.GroupLayout(pnlFoodExpense);
        pnlFoodExpense.setLayout(pnlFoodExpenseLayout);
        pnlFoodExpenseLayout.setHorizontalGroup(
            pnlFoodExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFoodExpenseLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlFoodExpenseLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnFoodExpense)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFoodExpenseLayout.setVerticalGroup(
            pnlFoodExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFoodExpenseLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFoodExpense)
                .addContainerGap())
        );

        pnlTransportExpense.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bttnEducationExpense.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        bttnEducationExpense.setText("Education");
        bttnEducationExpense.setToolTipText("Click to add Transport Expense information.");
        bttnEducationExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEducationExpenseActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Education.png"))); // NOI18N

        javax.swing.GroupLayout pnlTransportExpenseLayout = new javax.swing.GroupLayout(pnlTransportExpense);
        pnlTransportExpense.setLayout(pnlTransportExpenseLayout);
        pnlTransportExpenseLayout.setHorizontalGroup(
            pnlTransportExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTransportExpenseLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(bttnEducationExpense)
                .addGap(61, 61, 61))
            .addGroup(pnlTransportExpenseLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTransportExpenseLayout.setVerticalGroup(
            pnlTransportExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTransportExpenseLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(bttnEducationExpense)
                .addContainerGap())
        );

        pnlClothesExpense.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnClothesExpense.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnClothesExpense.setText("Clothes");
        btnClothesExpense.setToolTipText("Click to add Clothes Expense information.");
        btnClothesExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClothesExpenseActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ClothesExpense.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout pnlClothesExpenseLayout = new javax.swing.GroupLayout(pnlClothesExpense);
        pnlClothesExpense.setLayout(pnlClothesExpenseLayout);
        pnlClothesExpenseLayout.setHorizontalGroup(
            pnlClothesExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClothesExpenseLayout.createSequentialGroup()
                .addGroup(pnlClothesExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClothesExpenseLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnClothesExpense))
                    .addGroup(pnlClothesExpenseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlClothesExpenseLayout.setVerticalGroup(
            pnlClothesExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClothesExpenseLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClothesExpense)
                .addContainerGap())
        );

        pnlEntertainmentExpense.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLivingHouseExpense.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnLivingHouseExpense.setText("Living House");
        btnLivingHouseExpense.setToolTipText("Click to add Entertainment Expense information.");
        btnLivingHouseExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivingHouseExpenseActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Living House.png"))); // NOI18N

        javax.swing.GroupLayout pnlEntertainmentExpenseLayout = new javax.swing.GroupLayout(pnlEntertainmentExpense);
        pnlEntertainmentExpense.setLayout(pnlEntertainmentExpenseLayout);
        pnlEntertainmentExpenseLayout.setHorizontalGroup(
            pnlEntertainmentExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEntertainmentExpenseLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(pnlEntertainmentExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlEntertainmentExpenseLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnLivingHouseExpense)))
                .addContainerGap())
        );
        pnlEntertainmentExpenseLayout.setVerticalGroup(
            pnlEntertainmentExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEntertainmentExpenseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLivingHouseExpense)
                .addContainerGap())
        );

        pnlOtherCategoryExpense.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bttnOtherCategory.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        bttnOtherCategory.setText("Other Category");
        bttnOtherCategory.setToolTipText("Click to add information for Other Category.");
        bttnOtherCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnOtherCategoryActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Plus.png"))); // NOI18N

        javax.swing.GroupLayout pnlOtherCategoryExpenseLayout = new javax.swing.GroupLayout(pnlOtherCategoryExpense);
        pnlOtherCategoryExpense.setLayout(pnlOtherCategoryExpenseLayout);
        pnlOtherCategoryExpenseLayout.setHorizontalGroup(
            pnlOtherCategoryExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOtherCategoryExpenseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOtherCategoryExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlOtherCategoryExpenseLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bttnOtherCategory)))
                .addGap(25, 25, 25))
        );
        pnlOtherCategoryExpenseLayout.setVerticalGroup(
            pnlOtherCategoryExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOtherCategoryExpenseLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bttnOtherCategory)
                .addContainerGap())
        );

        btnReturnToMainMenu.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnReturnToMainMenu.setText("Return To Main Menu");
        btnReturnToMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnToMainMenuActionPerformed(evt);
            }
        });

        btnRegisterCard.setText("New Card");
        btnRegisterCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterCardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlFoodExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlClothesExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTransportExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEntertainmentExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlOtherCategoryExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHealthExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnRegisterCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReturnToMainMenu)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlTransportExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFoodExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHealthExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlClothesExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEntertainmentExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlOtherCategoryExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturnToMainMenu)
                    .addComponent(btnRegisterCard))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnuPersonalFinances.setText("Personal Finances");
        mnuPersonalFinances.setToolTipText("Click to display a menu.");

        mnuItmLogOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnuItmLogOut.setText("Log out");
        mnuItmLogOut.setToolTipText("Click to log out and change the user.");
        mnuItmLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmLogOutActionPerformed(evt);
            }
        });
        mnuPersonalFinances.add(mnuItmLogOut);

        mnuItmExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        mnuItmExit.setText("Exit");
        mnuItmExit.setToolTipText("Click to exit.");
        mnuItmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmExitActionPerformed(evt);
            }
        });
        mnuPersonalFinances.add(mnuItmExit);

        jMenuBar1.add(mnuPersonalFinances);

        mnuCustomerInformation.setText("Customer Information");
        mnuCustomerInformation.setToolTipText("Click to display a menu.");

        mnuIncome.setText("Income");
        mnuIncome.setToolTipText("Click to display a submenu.");

        mnuItmSalary.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuItmSalary.setText("Salary");
        mnuItmSalary.setToolTipText("Click to add Salary information.");
        mnuItmSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmSalaryActionPerformed(evt);
            }
        });
        mnuIncome.add(mnuItmSalary);

        mnuItmPocketMoney.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuItmPocketMoney.setText("Pocket Money");
        mnuItmPocketMoney.setToolTipText("Click to add Pocket Money information.");
        mnuItmPocketMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmPocketMoneyActionPerformed(evt);
            }
        });
        mnuIncome.add(mnuItmPocketMoney);

        mnuItmOtherCategoryIncome.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mnuItmOtherCategoryIncome.setText("Other Category");
        mnuItmOtherCategoryIncome.setToolTipText("Click to add Other Category information.");
        mnuItmOtherCategoryIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmOtherCategoryIncomeActionPerformed(evt);
            }
        });
        mnuIncome.add(mnuItmOtherCategoryIncome);

        mnuCustomerInformation.add(mnuIncome);

        mnuExpense.setText("Expense");
        mnuExpense.setToolTipText("Click to display a submenu.");

        mnuItmFood.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        mnuItmFood.setText("Food");
        mnuItmFood.setToolTipText("Click to add Food Expense information.");
        mnuItmFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmFoodActionPerformed(evt);
            }
        });
        mnuExpense.add(mnuItmFood);

        mnuItmEducation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnuItmEducation.setText("Education");
        mnuItmEducation.setToolTipText("Click to add Transport Expense information.");
        mnuItmEducation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmEducationActionPerformed(evt);
            }
        });
        mnuExpense.add(mnuItmEducation);

        mnuItmHealth.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mnuItmHealth.setText("Health");
        mnuItmHealth.setToolTipText("Click to add Health Expense infomation.");
        mnuItmHealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmHealthActionPerformed(evt);
            }
        });
        mnuExpense.add(mnuItmHealth);

        mnuItmClothes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnuItmClothes.setText("Clothes");
        mnuItmClothes.setToolTipText("Click to add Clothes Expense information.");
        mnuItmClothes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmClothesActionPerformed(evt);
            }
        });
        mnuExpense.add(mnuItmClothes);

        mnuItmLivingHouse.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnuItmLivingHouse.setText("Living House");
        mnuItmLivingHouse.setToolTipText("Click to add Entertainment Expense information.");
        mnuItmLivingHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmLivingHouseActionPerformed(evt);
            }
        });
        mnuExpense.add(mnuItmLivingHouse);

        mnuItmOtherCategoryExpense.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuItmOtherCategoryExpense.setText("Other Category");
        mnuItmOtherCategoryExpense.setToolTipText("Click to add Other Category information.");
        mnuItmOtherCategoryExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmOtherCategoryExpenseActionPerformed(evt);
            }
        });
        mnuExpense.add(mnuItmOtherCategoryExpense);

        mnuCustomerInformation.add(mnuExpense);

        mnuStatement.setText("Statement");
        mnuStatement.setToolTipText("Click to display a submenu.");

        mnuItmTotalIncome.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuItmTotalIncome.setText("Total Income");
        mnuItmTotalIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmTotalIncomeActionPerformed(evt);
            }
        });
        mnuStatement.add(mnuItmTotalIncome);

        mnuItmTotalExpense.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuItmTotalExpense.setText("Total Expense");
        mnuItmTotalExpense.setToolTipText("Click to see Total Expense table.");
        mnuItmTotalExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmTotalExpenseActionPerformed(evt);
            }
        });
        mnuStatement.add(mnuItmTotalExpense);

        mnuItmTotalBalance.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuItmTotalBalance.setText("Total Balance");
        mnuItmTotalBalance.setToolTipText("Click to see Total Balance table.");
        mnuItmTotalBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmTotalBalanceActionPerformed(evt);
            }
        });
        mnuStatement.add(mnuItmTotalBalance);

        mnuCustomerInformation.add(mnuStatement);

        jMenuBar1.add(mnuCustomerInformation);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHealthExpenseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnHealthExpenseActionPerformed
    {//GEN-HEADEREND:event_btnHealthExpenseActionPerformed
        // TODO add your handling code here:
        FrmExpenseHealth frmExpenseHealth = new FrmExpenseHealth();
        frmExpenseHealth.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHealthExpenseActionPerformed

    private void btnFoodExpenseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFoodExpenseActionPerformed
    {//GEN-HEADEREND:event_btnFoodExpenseActionPerformed
        FrmExpenseFood frmExpenseFood = new FrmExpenseFood();
        frmExpenseFood.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnFoodExpenseActionPerformed

    private void bttnEducationExpenseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bttnEducationExpenseActionPerformed
    {//GEN-HEADEREND:event_bttnEducationExpenseActionPerformed
        FrmExpenseEducation frmExpenseEducation = new FrmExpenseEducation();
        frmExpenseEducation.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttnEducationExpenseActionPerformed

    private void btnClothesExpenseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnClothesExpenseActionPerformed
    {//GEN-HEADEREND:event_btnClothesExpenseActionPerformed
        this.setVisible(false);
        new FrmExpenseClothes().setVisible(true);
    }//GEN-LAST:event_btnClothesExpenseActionPerformed

    private void btnLivingHouseExpenseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLivingHouseExpenseActionPerformed
    {//GEN-HEADEREND:event_btnLivingHouseExpenseActionPerformed
        FrmExpenseLivingHouse frmExpenseLivingHouse = new FrmExpenseLivingHouse();
        frmExpenseLivingHouse.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLivingHouseExpenseActionPerformed

    private void bttnOtherCategoryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bttnOtherCategoryActionPerformed
    {//GEN-HEADEREND:event_bttnOtherCategoryActionPerformed
        FrmExpenseOtherCategory frmExpenseEntertainment = new FrmExpenseOtherCategory();
        frmExpenseEntertainment.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttnOtherCategoryActionPerformed

    private void btnReturnToMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnToMainMenuActionPerformed
        this.setVisible(false);
        new FrmMainMenu().setVisible(true);
    }//GEN-LAST:event_btnReturnToMainMenuActionPerformed

    private void mnuItmLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmLogOutActionPerformed
        this.setVisible(false);
        new FrmLogin().setVisible(true);
    }//GEN-LAST:event_mnuItmLogOutActionPerformed

    private void mnuItmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuItmExitActionPerformed

    private void mnuItmSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmSalaryActionPerformed
        this.setVisible(false);
        new FrmIncomeSalary().setVisible(true);
    }//GEN-LAST:event_mnuItmSalaryActionPerformed

    private void mnuItmPocketMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmPocketMoneyActionPerformed
        this.setVisible(false);
        new FrmIncomePocketMoney().setVisible(true);
    }//GEN-LAST:event_mnuItmPocketMoneyActionPerformed

    private void mnuItmOtherCategoryIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmOtherCategoryIncomeActionPerformed
        this.setVisible(false);
        new FrmOtherCategoryIncome().setVisible(true);
    }//GEN-LAST:event_mnuItmOtherCategoryIncomeActionPerformed

    private void mnuItmFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmFoodActionPerformed
        this.setVisible(false);
        new FrmExpenseFood().setVisible(true);
    }//GEN-LAST:event_mnuItmFoodActionPerformed

    private void mnuItmEducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmEducationActionPerformed
        this.setVisible(false);
        new FrmExpenseEducation().setVisible(true);
    }//GEN-LAST:event_mnuItmEducationActionPerformed

    private void mnuItmHealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmHealthActionPerformed
        this.setVisible(false);
        new FrmExpenseHealth().setVisible(true);
    }//GEN-LAST:event_mnuItmHealthActionPerformed

    private void mnuItmClothesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmClothesActionPerformed
        this.setVisible(false);
        new FrmExpenseClothes().setVisible(true);
    }//GEN-LAST:event_mnuItmClothesActionPerformed

    private void mnuItmLivingHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmLivingHouseActionPerformed
        this.setVisible(false);
        new FrmExpenseLivingHouse().setVisible(true);
    }//GEN-LAST:event_mnuItmLivingHouseActionPerformed

    private void mnuItmOtherCategoryExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmOtherCategoryExpenseActionPerformed
        this.setVisible(false);
        new FrmExpenseOtherCategory().setVisible(true);
    }//GEN-LAST:event_mnuItmOtherCategoryExpenseActionPerformed

    private void mnuItmTotalIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmTotalIncomeActionPerformed
        this.setVisible(false);
        new FrmTableIncome().setVisible(true);
    }//GEN-LAST:event_mnuItmTotalIncomeActionPerformed

    private void mnuItmTotalExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmTotalExpenseActionPerformed
        this.setVisible(false);
        new FrmTableExpense().setVisible(true);
    }//GEN-LAST:event_mnuItmTotalExpenseActionPerformed

    private void mnuItmTotalBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmTotalBalanceActionPerformed
        this.setVisible(false);
        new FrmTotalBalance().setVisible(true);
    }//GEN-LAST:event_mnuItmTotalBalanceActionPerformed

    private void btnRegisterCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterCardActionPerformed
        // TODO add your handling code here:
        new FrmCardRegister().setVisible(true);
    }//GEN-LAST:event_btnRegisterCardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmExpense().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClothesExpense;
    private javax.swing.JButton btnFoodExpense;
    private javax.swing.JButton btnHealthExpense;
    private javax.swing.JButton btnLivingHouseExpense;
    private javax.swing.JButton btnRegisterCard;
    private javax.swing.JButton btnReturnToMainMenu;
    private javax.swing.JButton bttnEducationExpense;
    private javax.swing.JButton bttnOtherCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnuCustomerInformation;
    private javax.swing.JMenu mnuExpense;
    private javax.swing.JMenu mnuIncome;
    private javax.swing.JMenuItem mnuItmClothes;
    private javax.swing.JMenuItem mnuItmEducation;
    private javax.swing.JMenuItem mnuItmExit;
    private javax.swing.JMenuItem mnuItmFood;
    private javax.swing.JMenuItem mnuItmHealth;
    private javax.swing.JMenuItem mnuItmLivingHouse;
    private javax.swing.JMenuItem mnuItmLogOut;
    private javax.swing.JMenuItem mnuItmOtherCategoryExpense;
    private javax.swing.JMenuItem mnuItmOtherCategoryIncome;
    private javax.swing.JMenuItem mnuItmPocketMoney;
    private javax.swing.JMenuItem mnuItmSalary;
    private javax.swing.JMenuItem mnuItmTotalBalance;
    private javax.swing.JMenuItem mnuItmTotalExpense;
    private javax.swing.JMenuItem mnuItmTotalIncome;
    private javax.swing.JMenu mnuPersonalFinances;
    private javax.swing.JMenu mnuStatement;
    private javax.swing.JPanel pnlClothesExpense;
    private javax.swing.JPanel pnlEntertainmentExpense;
    private javax.swing.JPanel pnlFoodExpense;
    private javax.swing.JPanel pnlHealthExpense;
    private javax.swing.JPanel pnlOtherCategoryExpense;
    private javax.swing.JPanel pnlTransportExpense;
    // End of variables declaration//GEN-END:variables
}
