/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.personalfinances.view;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import ec.edu.espe.personalfinances.model.Income;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.*;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author OneTouchEspe
 */
public class FrmTableIncome extends javax.swing.JFrame {

    public static DefaultTableModel model;
    public static int counter = 0;

    /**
     * Creates new form FrmTable
     */
    public static String directory = System.getProperties().getProperty("user.dir");

    public FrmTableIncome() {
        initComponents();
        UploadInterface();
        UploadData();
        txtTotalIncome.setText(Double.toString(totalIncome()));
        this.setLocationRelativeTo(null);

    }

    public double totalIncome() {
        double count = tblIncomeTable.getRowCount();
        double addition = 0;
        for (int i = 0; i < count; i++) {

            addition = addition + Double.parseDouble(tblIncomeTable.getValueAt(i, 1).toString());
            addition = Math.round(addition * 100) / 100d;

        }
        return addition;
    }

    public void UploadInterface() {

        String data[][] = {};
        String column[] = {"Income", "Amount", "Date"};
        model = new DefaultTableModel(data, column);
        tblIncomeTable.setModel(model);

    }

    public static void UploadData() {

        JSONObject jsonObjectRegister = new JSONObject();
        JSONArray jsonArrayRegister = new JSONArray();
        JSONParser jsonParserRegister = new JSONParser();

        File file2 = null;
        FileReader fileReader = null;
        BufferedReader bufferReader = null;
        ArrayList<Income> incomeData = new ArrayList<>();
        Gson gson = new Gson();
        String line;
        String incomeJson = "";
        try {

            file2 = new File(directory + "//Income.json");
            fileReader = new FileReader(file2);
            bufferReader = new BufferedReader(fileReader);

            while ((line = bufferReader.readLine()) != null) {
                System.out.println(line);

                incomeJson = incomeJson + line;

            }

            incomeJson = incomeJson.replace("\\", "");
            java.lang.reflect.Type incomeType = new TypeToken<ArrayList<Income>>() {
            }.getType();

            incomeData = gson.fromJson(incomeJson, incomeType);

            for (Income incomedType : incomeData) {
                model.insertRow(counter, new Object[]{});
                model.setValueAt(incomedType.getIncome(), counter, 0);
                model.setValueAt(incomedType.getAmount(), counter, 1);
                model.setValueAt(incomedType.getDate(), counter, 2);

            }

        } catch (Exception e) {

        } finally {
            try {
                if (null != fileReader) {
                    fileReader.close();
                }
            } catch (IOException e2) {
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIncomeTable = new javax.swing.JTable();
        bttnReturnStatements = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblTotalIncome = new javax.swing.JLabel();
        txtTotalIncome = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Income's Statement");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("INCOMES");

        tblIncomeTable.setAutoCreateRowSorter(true);
        tblIncomeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIncomeTable);

        bttnReturnStatements.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        bttnReturnStatements.setText("Return");
        bttnReturnStatements.setToolTipText("Click to return to Stament menu.");
        bttnReturnStatements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnReturnStatementsActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/TotalIncome.png"))); // NOI18N

        lblTotalIncome.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblTotalIncome.setText("Total Income:");

        txtTotalIncome.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        btnPrint.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotalIncome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addComponent(btnPrint)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bttnReturnStatements))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnReturnStatements)
                    .addComponent(lblTotalIncome)
                    .addComponent(txtTotalIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrint))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnReturnStatementsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bttnReturnStatementsActionPerformed
    {//GEN-HEADEREND:event_bttnReturnStatementsActionPerformed
        // TODO add your handling code here:
        FrmStatement frmStatements = new FrmStatement();
        frmStatements.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttnReturnStatementsActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        MessageFormat header = new MessageFormat("Income Report");
        MessageFormat footer = new MessageFormat("Page{0, number, integer}");
        try {
            tblIncomeTable.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTableIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTableIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTableIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTableIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTableIncome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton bttnReturnStatements;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalIncome;
    public javax.swing.JTable tblIncomeTable;
    private javax.swing.JTextField txtTotalIncome;
    // End of variables declaration//GEN-END:variables
}
