/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.personalfinances.view;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import ec.edu.espe.personalfinances.model.Expense;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author OneTouchEspe
 */
public class FrmTableExpense extends javax.swing.JFrame {

    public static DefaultTableModel model;
    public static int counter = 0;
    

    /**
     * Creates new form FrmExpenses
     */
    public static String directory = System.getProperties().getProperty("user.dir");

    public FrmTableExpense() {
        initComponents();
        UploadInterface();
        UploadData();
        txtTotalExpense.setText(Double.toString(totalExpense()));
        this.setLocationRelativeTo(null);
    }

    public double totalExpense() {
        double count = tblExpenseTable.getRowCount();
        double addition = 0;
        
        for (int i = 0; i < count; i++) {

            addition = addition + Double.parseDouble(tblExpenseTable.getValueAt(i, 2).toString());
            addition = Math.round(addition * 100) / 100d;
        }
        return addition;
    }

    public void UploadInterface() {

        String data[][] = {};
        String column[] = {"Expense ", "Establishment", "Amount", "Payment Method", "Date"};
        model = new DefaultTableModel(data, column);

        tblExpenseTable.setModel(model);

    }

    public static void UploadData() {

        JSONObject jsonObjectRegister = new JSONObject();
        JSONArray jsonArrayRegister = new JSONArray();
        JSONParser jsonParserRegister = new JSONParser();

        File file2 = null;
        FileReader fileReader = null;
        BufferedReader bufferReader = null;
        ArrayList<Expense> expenseData = new ArrayList<>();
        Gson gson = new Gson();
        String line;
        String expenseJson = "";
        try {

            file2 = new File(directory + "//Expense.json");
            fileReader = new FileReader(file2);
            bufferReader = new BufferedReader(fileReader);

            while ((line = bufferReader.readLine()) != null) {
                System.out.println(line);

                expenseJson = expenseJson + line;

            }

            expenseJson = expenseJson.replace("\\", "");
            java.lang.reflect.Type expnseType = new TypeToken<ArrayList<Expense>>() {
            }.getType();

            expenseData = gson.fromJson(expenseJson, expnseType);

            for (Expense expensedType : expenseData) {
                model.insertRow(counter, new Object[]{});
                model.setValueAt(expensedType.getExpense(), counter, 0);
                model.setValueAt(expensedType.getEstablishment(), counter, 1);
                model.setValueAt(expensedType.getAmount(), counter, 2);
                model.setValueAt(expensedType.getPaymentMethod(), counter, 3);
                model.setValueAt(expensedType.getDate(), counter, 4);
   

            }

        } catch (Exception e) {

        } finally {
            try {
                if (null != fileReader) {
                    fileReader.close();
                }
            } catch (IOException e2) {
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExpenseTable = new javax.swing.JTable();
        bttnReturnStatements = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTotalExpense = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expense's Statement");
        setBackground(new java.awt.Color(204, 255, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("EXPENSES");

        tblExpenseTable.setAutoCreateRowSorter(true);
        tblExpenseTable.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tblExpenseTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblExpenseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblExpenseTable);

        bttnReturnStatements.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        bttnReturnStatements.setText("Return");
        bttnReturnStatements.setToolTipText("Click to return to Stament menu.");
        bttnReturnStatements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnReturnStatementsActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/TotalExpense.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Total Expense: ");

        txtTotalExpense.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTotalExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalExpenseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnReturnStatements)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttnReturnStatements, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtTotalExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnReturnStatementsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bttnReturnStatementsActionPerformed
    {//GEN-HEADEREND:event_bttnReturnStatementsActionPerformed
        // TODO add your handling code here:
        FrmStatement frmStatements = new FrmStatement();
        frmStatements.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttnReturnStatementsActionPerformed

    private void txtTotalExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalExpenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalExpenseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTableExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTableExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTableExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTableExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTableExpense().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnReturnStatements;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblExpenseTable;
    private javax.swing.JTextField txtTotalExpense;
    // End of variables declaration//GEN-END:variables
}
