/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.virtualgamestore.gui.view;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import ec.edu.espe.virtualgamestore.controller.AccessoryReader;

import ec.edu.espe.virtualgamestore.model.Accessory;

import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JavaMasters
 */
public class FrmAccessory extends javax.swing.JFrame {

    private DefaultTableModel model;
    int count = 0;
    private final String directory = System.getProperties().getProperty("user.dir");
    Background screen = new Background();

    /**
     * Creates new form FrmAccessory
     */
    public FrmAccessory() throws IOException {
        this.setContentPane(screen);
        AccessoryReader reader = new AccessoryReader();
        initComponents();
        setLocationRelativeTo(null);

        tittleTable();
        accessoryData();

       
        ImageIcon icon2 = new ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/Game.png"));
        icon2 = new ImageIcon(icon2.getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));

        mnuGame.setIcon(icon2);

        

        ImageIcon icon4 = new ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/AccessoriesLogo.png"));
        icon4 = new ImageIcon(icon4.getImage().getScaledInstance(400, 100, Image.SCALE_DEFAULT));

        LbLogoAcces.setIcon(icon4);

        ImageIcon icon5 = new ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/Cart.png"));
        icon5 = new ImageIcon(icon5.getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT));

        mnuCart.setIcon(icon5);

    }

    public void tittleTable() {

        String data[][] = {};
        String column[] = {"Id ", "Name", "Price", "Color",};
        model = new DefaultTableModel(data, column);

        tblAccesories.setModel(model);

    }

    public void accessoryData() throws IOException {

        ArrayList<Accessory> accessoryData = new ArrayList<>();
        AccessoryReader reader = new AccessoryReader();
        accessoryData = reader.readFromFile();
        

        for (Accessory type : accessoryData) {
            model.insertRow(count, new Object[]{});
            model.setValueAt(type.getId(), count, 0);
            model.setValueAt(type.getName(), count, 1);
            model.setValueAt(type.getPrice(), count, 2);
            model.setValueAt(type.getColor(), count, 3);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbLogoAcces = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAccesories = new javax.swing.JTable();
        btnPrint = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuVirtualGameStore = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuGame = new javax.swing.JMenu();
        mnuCart = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        tblAccesories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblAccesories);

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        MnuVirtualGameStore.setText("Virtual Game Store");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Main Menu");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MnuVirtualGameStore.add(jMenuItem3);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MnuVirtualGameStore.add(jMenuItem1);

        jMenuBar1.add(MnuVirtualGameStore);

        mnuGame.setText("Games");
        mnuGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuGameMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuGame);

        mnuCart.setText("Cart");
        mnuCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuCartMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuCart);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(LbLogoAcces, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(btnPrint)))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPrint)
                        .addGap(145, 145, 145)))
                .addComponent(LbLogoAcces, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuGameMouseClicked
        this.setVisible(false);
        try {
            new FrmGame().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FrmAccessory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuGameMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FrmPrincipalMenuUser().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mnuCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCartMouseClicked
        new FrmCart().setVisible(true);
        dispose();
    }//GEN-LAST:event_mnuCartMouseClicked

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        MessageFormat header = new MessageFormat("Accessories");
        MessageFormat footer = new MessageFormat("Page{0, number, integer}");
        try {
            tblAccesories.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[]) throws IOException {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAccessory.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAccessory.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAccessory.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAccessory.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmAccessory().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FrmAccessory.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbLogoAcces;
    private javax.swing.JMenu MnuVirtualGameStore;
    private javax.swing.JButton btnPrint;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu mnuCart;
    private javax.swing.JMenu mnuGame;
    private javax.swing.JTable tblAccesories;
    // End of variables declaration//GEN-END:variables
class Background extends JPanel {

        private Image image;

        public void paint(Graphics g) {
            image = new ImageIcon(getClass().getResource("/ec/edu/espe/virtualgamestore/pictures/fontA.png")).getImage();

            g.drawImage(image, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
}
